//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "custom_columns")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub datatype: String,
    #[sea_orm(column_type = "custom(\"BOOL\")")]
    pub mark_for_delete: String,
    #[sea_orm(column_type = "custom(\"BOOL\")")]
    pub editable: String,
    #[sea_orm(column_type = "Text")]
    pub display: String,
    #[sea_orm(column_type = "custom(\"BOOL\")")]
    pub is_multiple: String,
    #[sea_orm(column_type = "custom(\"BOOL\")")]
    pub normalized: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
