//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "last_read_positions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub book: i32,
    #[sea_orm(column_type = "Text")]
    pub format: String,
    #[sea_orm(column_type = "Text")]
    pub user: String,
    #[sea_orm(column_type = "Text")]
    pub device: String,
    #[sea_orm(column_type = "Text")]
    pub cfi: String,
    pub epoch: Decimal,
    pub pos_frac: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
