//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod authors;
pub mod books;
pub mod books_authors_link;
pub mod books_languages_link;
pub mod books_plugin_data;
pub mod books_publishers_link;
pub mod books_ratings_link;
pub mod books_series_link;
pub mod books_tags_link;
pub mod comments;
pub mod conversion_options;
pub mod custom_columns;
pub mod data;
pub mod feeds;
pub mod identifiers;
pub mod languages;
pub mod last_read_positions;
pub mod library_id;
pub mod metadata_dirtied;
pub mod preferences;
pub mod publishers;
pub mod ratings;
pub mod series;
pub mod tags;
